In [8]:
import numpy as np

a = np.arange(6).reshape((2,3))
print(a)
print("axis 0 ", a.sum(axis=0))
print("axis 1 ", a.sum(axis=1))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))
print("bias ", a + np.array([[1],[2]]))

[[0 1 2]
 [3 4 5]]
axis 0  [3 5 7]
axis 1  [ 3 12]
[1 1 1]
[2 2]
bias  [[1 2 3]
 [5 6 7]]


In [6]:
import numpy as np
def softmax(x):
    dev = np.sum(np.exp(x), axis=0)
    #print("softmax shape", dev.shape)
    dev.shape = [1, dev.size]
    return np.exp(x) / dev

x = np.array(
[[-1,0,1],
 [1,1,1],
 [0,1,1]])

print(x)
print(softmax(x))

[[-1  0  1]
 [ 1  1  1]
 [ 0  1  1]]
[[ 0.09003057  0.1553624   0.33333333]
 [ 0.66524096  0.4223188   0.33333333]
 [ 0.24472847  0.4223188   0.33333333]]


In [11]:
import numpy as np
def ReLU(x):
    mask = x < 0
    x[mask] = 0
    return x

x = np.array(
[[-1,0,1],
 [ 1,2,-3]])
print(ReLU(x))
jj

[[0 0 1]
 [1 2 0]]


ValueError: a must be 1-dimensional

In [14]:
import numpy as np
print(np.random.randint(0,5,10))

[0 3 0 3 4 2 0 1 4 1]
